name: Deploy to dev

on:
  push:
    branches:
      - dev

env:
  NODE_VERSION: '16.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to dev/staging

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 'Use Node.js v${{ env.NODE_VERSION }}'
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tvl-labs'

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: |
            node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build
        shell: bash
        run: yarn build && yarn export
        env:
          NEXT_PUBLIC_IS_PRODUCTION: "true"
          NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: "https://safe-cgw.khalani.network"
          NEXT_PUBLIC_SAFE_VERSION: "1.3.0"
          NEXT_PUBLIC_WC_PROJECT_ID: "a81740090b1571e5737ff0cdfbad34ab"
          NEXT_PUBLIC_WC_BRIDGE: "https://safe-walletconnect.safe.global"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Dev
      - name: Deploy to the dev S3
        if: github.ref == 'refs/heads/dev'
        env:
          BUCKET: s3://${{ secrets.AWS_DEVELOPMENT_BUCKET_NAME }}
        run: bash ./scripts/github/s3_upload.sh