# web-core image is meant to be used only by our safe-infrastructure repository

name: Deploy to Dockerhub

on:
  push:
    branches:
      - dev
  release:
    types: [ released ]

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        cache-from: type=registry,ref=ghcr.io/${{github.repository}}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{github.repository}}:buildcache,mode=max
        tags: ghcr.io/${{github.repository}}:latest
        build-args: |
          BUILDKIT_INLINE_CACHE=1